version: "3.8"
services:
  backend:
    container_name: fastAPI_bk
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

  database:
    container_name: postgres_db
    image: postgres:15.4-alpine
    restart: always

    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tapwd
      - POSTGRES_DB=test_db
    networks:
      - custom

  test_database:
    container_name: postgres_testdb
    image: postgres:15.4-alpine
    restart: always

    ports: 
      - "54320:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tapwd
      - POSTGRES_DB=test_db
    networks:
      - custom

networks:
  custom:
    driver: bridge